### ISSUE TITLE
[MACRO] Initial Builder Design

### ISSUE THREAD

**Issue by move47** [EspressoSystems/hotshot-builder-core#13]
- [x] Rough builder state specifications #7
- [x] Builder should be able to receive event messages from Hotshot in non-blocking mode #8
- [x] Include Hotshot types in the rough design #11
